mantisbt:
  image: nutthaphon/mantis:latest
  volumes:
    - /home/nutt/Docker/mantisbt/html:/var/www/html
    - /home/nutt/Docker/mantisbt/php:/usr/local/etc/php
  ports:
    - "8989:80"
    - "8922:22"
  links:
    - mysql
  restart: "no"
mysql:
  image: mariadb:latest
  ports:
    - "3306:3306"
    - "3322:22"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantisbt
    - MYSQL_PASSWORD=mantisbt
  volumes:
    - '/home/nutt/Docker/mantisbt/mysql:/var/lib/mysql'
    - '/home/nutt/Docker/mantisbt/mysql.conf/mysql:/etc/mysql'
  restart: "no"
