mantisbt:
  image: nutthaphon/mantisbt
  volumes:
    - /home/nc-user/Docker/mantisbt/html:/var/www/html
    - /home/nc-user/Docker/mantisbt/php:/usr/local/etc/php
  ports:
    - "80:80"
    - "8922:22"
  links:
    - mysql
  restart: "always"
mysql:
  image: mariadb:latest
  ports:
    - "3306:3306"
    - "3322:22"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantisbt
    - MYSQL_PASSWORD=mantisbt
  volumes:
    - '/home/nc-user/Docker/mantisbt/mysql:/var/lib/mysql'
    - '/home/nc-user/Docker/mantisbt/mysql.conf.d:/etc/mysql'
  restart: "always"
